name: Build Custom OpenCV.js
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.53

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          apt-get update && apt-get install -y python3-pip git cmake

      - name: Clone OpenCV
        run: |
          git clone --depth 1 --branch 4.x https://github.com/opencv/opencv.git

      - name: Build OpenCV.js
        run: |
          cp minimal_config.py opencv/platforms/js/minimal_config.py
          emcmake python3 opencv/platforms/js/build_js.py build_out \
            --build_wasm \
            --config "$GITHUB_WORKSPACE/opencv/platforms/js/minimal_config.py" \
            --cmake_option="-DCMAKE_BUILD_TYPE=Release" \
            --cmake_option="-DBUILD_opencv_dnn=OFF" \
            --cmake_option="-DBUILD_PROTOBUF=OFF" \
            --cmake_option="-DWITH_PROTOBUF=OFF"

      - name: Copy opencv.js to repo root
        run: cp build_out/bin/opencv.js opencv.js

      - name: Commit opencv.js to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add opencv.js
          git commit -m "Update opencv.js" || echo "Немає змін"
          git push
