name: Build Custom OpenCV.js
on:
  workflow_dispatch: # Дозволяє запустити збірку вручну кнопкою на сайті

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest # Запуск у чистому середовищі Emscripten

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          apt-get update && apt-get install -y python3-pip git cmake
          
      - name: Clone OpenCV
        run: |
          git clone --depth 1 --branch 4.x https://github.com/opencv/opencv.git

      - name: Build OpenCV.js
        run: |
          # Копіюємо наш конфіг всередину папки збірки OpenCV
          cp minimal_config.py opencv/platforms/js/minimal_config.py
          
          # Запускаємо збірку, розділивши прапорці CMake на окремі аргументи
          python3 opencv/platforms/js/build_js.py build_out \
            --build_wasm \
            --config opencv/platforms/js/minimal_config.py \
            --cmake_option="-DCMAKE_CXX_STANDARD=17" \
            --cmake_option="-DCMAKE_BUILD_TYPE=Release" \
            --cmake_option="-DENABLE_LTO=ON"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: opencv-js-custom
          path: build_out/bin/opencv.js
